---
title: ""
---

## Módulo I. Requisitos Básicos

```{r temario_modulo_I, echo=FALSE}
tibble::tibble(Tema = c("Instalar R y Rtools",
                        "IDEs & RStudio",
                        "Instalación de Paquetes desde CRAN, github y archivo",
                        "Instalación de Paquetes para el análisis espacial",
                        "Datos Básicos para elaborar un mapa",
                        "Mi primer mapa en R",
                        "Tipos de Datos Espaciales y el dengueverse en R"),
               Instructor = c(rep("Felipe Antonio Dzul Manzanilla", times = 7))) |>
    reactable::reactable(defaultPageSize = 7,
                         theme = reactablefmtr::flatly(),
                         filterable = FALSE,
                         striped = TRUE,
                         minRows = 7,
                         resizable = TRUE, 
                         wrap = FALSE, 
                         bordered = TRUE)

```

## Módulo II. Operaciones espaciales.
```{r temario_modulo_II, echo=FALSE}
tibble::tibble(Tema = c("Datos Geográficos",
                        "Operaciones Básicas: Cinco Verbos",
                        "Operaciones Espaciales"),
               Instructor = c(rep("Felipe Antonio Dzul Manzanilla", times = 3))) |>
    reactable::reactable(defaultPageSize = 4,
                         theme = reactablefmtr::flatly(),
                         filterable = FALSE,
                         striped = TRUE,
                         minRows = 4,
                         resizable = TRUE, 
                         wrap = FALSE, 
                         bordered = TRUE)

```

## Módulo III. Mapas Estáticos
```{r temario_modulo_III, echo=FALSE}
tibble::tibble(Tema = c("Paquetes para elaborar mapas estáticos",
                        "Mapas estáticos de área",
                        "Mapas estáticos de puntos",
                        "Mapas estáticos de áreas & puntos"),
               Instructor = c(rep("Felipe Antonio Dzul Manzanilla", 
                                  times = 4))) |>
    reactable::reactable(defaultPageSize = 4,
                         theme = reactablefmtr::flatly(),
                         filterable = FALSE,
                         striped = TRUE,
                         minRows = 4,
                         resizable = TRUE, 
                         wrap = FALSE, 
                         bordered = TRUE)

```

## Módulo IV. Mapas Animados

```{r temario_modulo_IV, echo=FALSE}
tibble::tibble(Tema = c("Paquetes para elaborar mapas animados",
                        "Mapas animados de área",
                        "Mapas animados de puntos",
                        "Mapas estáticos de áreas & puntos"),
               Instructor = c(rep("Felipe Antonio Dzul Manzanilla", 
                                  times = 4))) |>
    reactable::reactable(defaultPageSize = 4,
                         theme = reactablefmtr::flatly(),
                         filterable = FALSE,
                         striped = TRUE,
                         minRows = 4,
                         resizable = TRUE, 
                         wrap = FALSE, 
                         bordered = TRUE)

```

## Módulo V. Mapas Interáctivos

```{r temario_modulo_V, echo=FALSE}
tibble::tibble(Tema = c("Paquetes para elaborar mapas animados",
                        "Mapas animados de área",
                        "Mapas animados de puntos",
                        "Mapas estáticos de áreas & puntos"),
               Instructor = c(rep("Felipe Antonio Dzul Manzanilla", 
                                  times = 4))) |>
    reactable::reactable(defaultPageSize = 4,
                         theme = reactablefmtr::flatly(),
                         filterable = FALSE,
                         striped = TRUE,
                         minRows = 4,
                         resizable = TRUE, 
                         wrap = FALSE, 
                         bordered = TRUE)

```

## Módulo VI. Mapas en 3D

```{r temario_modulo_VI, echo=FALSE}
tibble::tibble(Tema = c("Paquetes para elaborar mapas en 3D",
                        "Mapas 3D de área",
                        "Mapas 3D de puntos"),
               Instructor = c(rep("Felipe Antonio Dzul Manzanilla", 
                                  times = 3))) |>
    reactable::reactable(defaultPageSize = 4,
                         theme = reactablefmtr::flatly(),
                         filterable = FALSE,
                         striped = TRUE,
                         minRows = 4,
                         resizable = TRUE, 
                         wrap = FALSE, 
                         bordered = TRUE)

```


